# Generated by Django 5.1.7 on 2025-06-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_candidate_phone_alter_employer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
