# Generated by Django 5.1.7 on 2025-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_candidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
