# Generated by Django 5.2.1 on 2025-05-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0006_alter_approvals_unique_together'),
        ('Interview', '0003_interviewshedule_created_at_and_more'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewshedule',
            unique_together={('job', 'candidate', 'date')},
        ),
    ]
