# Generated by Django 5.2.1 on 2025-05-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0004_alter_interviewshedule_unique_together'),
    ]

    operations = [
    ]
