# Generated by Django 5.2.1 on 2025-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0006_interviewshedule_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewshedule',
            name='notification_read',
        ),
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('You missed', 'You missed')], default='Upcoming', max_length=20),
        ),
    ]
