# Generated by Django 5.2.1 on 2025-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0007_remove_interviewshedule_notification_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewshedule',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Selected', 'Selected'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected'), ('You missed', 'You missed')], default='Upcoming', max_length=20),
        ),
    ]
