# Generated by Django 5.1.7 on 2025-05-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0008_interviewshedule_notification_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected'), ('You missed', 'You missed')], default='Upcoming', max_length=20),
        ),
    ]
