# Generated by Django 5.1.7 on 2025-05-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0004_alter_applyedjobs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvals',
            name='job',
        ),
        migrations.AddField(
            model_name='approvals',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
