# Generated by Django 5.1.7 on 2025-05-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0005_remove_approvals_job_approvals_message'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvals',
            unique_together={('candidate', 'employer')},
        ),
    ]
