# Generated by Django 5.2.1 on 2025-05-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0006_alter_approvals_unique_together'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['employer', 'title'], name='Empjob_jobs_employe_a61d4b_idx'),
        ),
    ]
