# Generated by Django 5.2.1 on 2025-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0007_jobs_empjob_jobs_employe_a61d4b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyedjobs',
            name='status',
            field=models.CharField(choices=[('Application Send', 'Application Send'), ('Application Viewed', 'Application Viewed'), ('Resume Viewed', 'Resume Viewed'), ('Pending', 'Pending'), ('ShortListed', 'ShortListed'), ('Interview Scheduled', 'Interview Scheduled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Interview Cancelled', 'Interview Cancelled')], default='Application Send', max_length=20),
        ),
    ]
