# Generated by Django 5.1.7 on 2025-06-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0008_alter_applyedjobs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
