# Generated by Django 5.1.7 on 2025-05-21 03:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_employersubscription_job_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersubscription',
            name='subscribed_job',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
    ]
