# Generated by Django 5.1.7 on 2025-05-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_employersubscription_subscribed_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSlotAddOn',
        ),
    ]
