# Generated by Django 5.1.7 on 2025-06-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_delete_jobslotaddon'),
        ('user_account', '0004_alter_employer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employersubscription',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.employer'),
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='job_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='razorpay_subscription_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('restricted', 'Restricted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='subscribed_job',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
