# Generated by Django 5.1.7 on 2025-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatmessage_chatroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sample',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
