# Generated by Django 5.1.7 on 2025-05-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_chatmessage_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chatroom',
            field=models.ForeignKey(default=1, help_text='The chat room this message belongs to.', on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
