# Generated by Django 5.1.7 on 2025-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_id',
            field=models.CharField(blank=True, help_text='ID of the receiver.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_id',
            field=models.CharField(blank=True, help_text='ID of the sender.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sendername',
            field=models.CharField(blank=True, help_text='Name of the sender (e.g., candidate or employer name).', max_length=100, null=True),
        ),
    ]
