# Generated by Django 5.1.7 on 2025-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chatmessage_receiver_id_chatmessage_sender_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_id',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sendername',
            field=models.TextField(blank=True, help_text='Name of the sender (e.g., candidate or employer name).', max_length=100, null=True),
        ),
    ]
