# Generated by Django 5.1.7 on 2025-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_sender_receiver_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sample',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='se_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
