# Generated by Django 5.2.1 on 2025-05-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_chatmessage_sample_chatmessage_se_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
    ]
